baseURL: https://unhcr-dataviz.github.io/curated-data/
languageCode: 'en-us'
title: 'Curated data'
relativeURLS: false

markup:
  goldmark:
    renderer:
      unsafe: true

enableInlineShortcodes: true

ignoreFiles: [ "\\.qmd$", "\\.ipynb$", "\\.py$" ]

pygmentsuseclasses: true

permalinks:
  page:
    product-gallery: /product-gallery/:year/:month/:title/



